### ISSUE TITLE
Some constraints not enabled due to type bug.

### ISSUE THREAD

**Issue by EGalahad** [real-stanford/umi-on-legs#1]
![image](https://github.com/user-attachments/assets/450adff6-04c9-4f1d-913d-e5f43a53da7f)

As shown in the sceenshot, the `constraints` specifies more entries than the ones accepted by `self.constraint`, this likely is caused by the type of some `constraint.values()` is not a class, but a dict of arguments.

I wonder if this is these constraints are missed out intentionally or is this a bug?

**Comment by huy-ha** [comment]
Yep, this is intentional. Since the Hydra config system automatically instantiate dictionaries with a `_target_` field into an object of that type, this partial function type filtering removes all of the constraints that were disabled by removing the `_target_` field.

**Comment by EGalahad** [comment]
I see, cool!
