### ISSUE TITLE
iPhoneVIO ethernet connect problem

### ISSUE THREAD

**Issue by kajwang** [real-stanford/umi-on-legs#11]
Hi, thanks for your excellent work! Our team want to mount an iPhone as an odometry after going through your deployment details. But now we kind of stuck in connection problem.
We carefully follow the instructions here:
https://github.com/real-stanford/umi-on-legs/blob/d75c9c182d8044dadf53043612da2ffbf1936a97/real-wbc/docs/codebase_setup.md?plain=1#L54

Compile the project in Xcode, deploy in an iPhone 15. The software works well as we saw real-time coordinate. 
Set the ethernet ipconfig in iPhone.
Connect iPhone and go2 jetson by an ethernet cable. (connection is ok because we see light flick in go2 port)
Start the python script.
But the refresh button on app doesn't work and there is no msg in pose topic.

Is there anything we miss?

**Comment by Cata1ysttt** [comment]
> Hi, thanks for your excellent work! Our team want to mount an iPhone as an odometry after going through your deployment details. But now we kind of stuck in connection problem. We carefully follow the instructions here:
> 
> https://github.com/real-stanford/umi-on-legs/blob/d75c9c182d8044dadf53043612da2ffbf1936a97/real-wbc/docs/codebase_setup.md?plain=1#L54
> 
> Compile the project in Xcode, deploy in an iPhone 15. The software works well as we saw real-time coordinate. Set the ethernet ipconfig in iPhone. Connect iPhone and go2 jetson by an ethernet cable. (connection is ok because we see light flick in go2 port) Start the python script. But the refresh button on app doesn't work and there is no msg in pose topic.
> 
> Is there anything we miss?

Sorry to disturb, we compiled the project in Xcode to an iPhone 13 Pro, but nothing happened in my iPhone(no apps found) Is there anything we miss?

**Comment by yihuai-gao** [comment]
Thank you for your interest in our work! To clarify, is your iPhone properly connected to the local network of unitree Go2? . It only works under the ethernet port (which shares the LAN with the minipc inside Go2), while doesn't work through usb-ethernet extenders. You can also check the ip address again, whether both of them start with 192.168.123.xxx. 

To make sure it's not a problem of the Go2's jetson, you can also connect your iPhone to any of your linux computers. Similarly, you should first manually set the ip address of the iPhone and linux to 192.168.0.xxx (the last digits should be different for the two devices), netmask 255.255.255.0, gateway 192.168.0.1, and see whether it works.

**Comment by yihuai-gao** [comment]
Another potential solution: after connecting iphone with a linux computer, go to the network setup and just select `IPv4 -> Shared to other computers`. On you iPhone, just choose `Configure IP -> automatic` to get the ip address and your iphone will be inside the LAN of you computer automatically.

**Comment by Cata1ysttt** [comment]
Maybe you can try to manually set your ip of Linux on your App and then refresh. That works for me to solve the similar problem on a linux computer when manually setting the ip address of the iPhone and linux to 192.168.0.xxx.

**Comment by kajwang** [comment]
Thanks for your kind responses! 
We try both two settings (manually set IP address / shared to other computers) when connect iPhone to Linux machine. But the program logs the same error: 
ws://192.168.0.122:5555 is not an accepted origin. (further occurrences of this error will be logged with level INFO) or
ws://10.42.0.1:5555 is not an accepted origin. (further occurrences of this error will be logged with level INFO)

It is checked that port 5555 is not occupied.

**Comment by yihuai-gao** [comment]
Could you try using http:// and your address? I'm not sure about the protocol but the default should be http

**Comment by yihuai-gao** [comment]
It's wierd that your iPhone cannot connect to your computer. This may be because of your firewall settings on your linux machine as well as some network setup on your iphone. One thing to check is to turn off the firewall (check `ufw status` and turn it off if it is on). If still doesn't work, you can try to use a different iphone and a different linux machine. From our experiences, brand new iphones and linux computers shouldn't have such issues.

**Comment by yihuai-gao** [comment]
I just realized that we've also had this error during our experiments, but it seems that the socket.io server running on the linux machine can still receive messages from iphone, so we just ignored it :)

**Comment by kajwang** [comment]
We tried manually setting IP in jetson, and the system works.
Thanks for your support!
