### ISSUE TITLE
Problem met when mamba env create -f isaac.yml  

### ISSUE THREAD

**Issue by P1terQ** [real-stanford/umi-on-legs#2]
ERROR: Could not find a version that satisfies the requirement rsl-rl==2.0.1 (from versions: none)
ERROR: No matching distribution found for rsl-rl==2.0.1

There isn't a tag satisfying v2.0.1 in rsl_rl repo

**Comment by huy-ha** [comment]
Removed rsl-rl dependency in b195f01!
