### ISSUE TITLE
How is the random trajectories (No UMI Trajs) baseline trained?

### ISSUE THREAD

**Issue by ZhengmaoHe** [real-stanford/umi-on-legs#4]
Thank you for sharing your awesome code!

I am curious about how the target curves of random trajectories (No UMI Trajs) baseline are sampled? It seems that the difference in errors (especially position errors) is not significant, which makes me curious because intuitively, training only one tossing trajectory (overfitting) should be faster and converge better than training with random trajectories. Especially when the curves used for training and evaluation are the same.

**Comment by huy-ha** [comment]
Thank you for the kind words!

You can find the script to generate the random trajectories [in the codebase](https://github.com/real-stanford/umi-on-legs/blob/main/mani-centric-wbc/scripts/generate_random_trajectories.py).

Alos, great question! The position errors are averaged over the entire episode, which also includes the slow quasi-static grasping phase along with the pause afterwards to reach 17 seconds. On average, high error over a 0.5 ish second toss contributes relatively little to the 17 second average error. I'll update the numbers on the paper soon with numbers specific to the toss!

**Comment by huy-ha** [comment]
Oh also,
> intuitively, training only one tossing trajectory (overfitting) should be faster and converge better than training with random trajectories

We train on much more than just one tossing trajectory ;) We said 100 in the paper, but upon double checking the tossing.pkl trajectories file it's actually 101.

**Comment by ZhengmaoHe** [comment]
> On average, high error over a 0.5 ish second toss contributes relatively little to the 17 second average error.  

That makes sense and solves my confusion.

I apologize for missing some details and thank you very much for your detailed and patient answers.
Thanks again for your wonderful work, it is very inspiring to me!
