### ISSUE TITLE
ArXiv link in README.md is not correct

### ISSUE THREAD

**Issue by han-xudong** [real-stanford/umi-on-legs#5]
The ArXiv link in README.md is https://arxiv.org/abs/2307.14535, which presents "Scaling Up and Distilling Down: Language-Guided Robot Skill Acquisition".

**Comment by hanxudong159** [comment]
Also the Video link, https://www.cs.columbia.edu/~huy/scalingup/static/videos/scalingup.mp4

**Comment by huy-ha** [comment]
Thanks for pointing it out! I've fixed it along with another link in the README.md.
